{"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"Runtime.ImportModuleError\",\"errorMessage\":\"Unable to import module 'downloader_lambda': No module named 'downloader_lambda'\"}. Output:\n\u001b[32mSTART RequestId: 89a41541-4fb5-1f8a-e824-ef3947be43d2 Version: $LATEST\u001b[0m\n[ERROR] Runtime.ImportModuleError: Unable to import module 'downloader_lambda': No module named 'downloader_lambda'\n\u001b[32mEND RequestId: 89a41541-4fb5-1f8a-e824-ef3947be43d2\u001b[0m\n\u001b[32mREPORT RequestId: 89a41541-4fb5-1f8a-e824-ef3947be43d2\tInit Duration: 134.71 ms\tDuration: 2.98 ms\tBilled Duration: 3 ms\tMemory Size: 1536 MB\tMax Memory Used: 25 MB\t\u001b[0m","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 602, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 176, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 168, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 159, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 147, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 325, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 231, in run_lambda_executor\n    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}
